
export const ACTIONS = {
    LOGIN_ACTION:"LOGIN_ACTION",
    GET_USERS:"GET_USERS",
    GET_SELECTED_USER:"GET_SELECTED_USER",
    ADD_USER:"ADD_USER",
    DELETE_USER:"DELETE_USER",
    UPDATE_USER:"UPDATE_USER",
    UPDATE_ADMIN:"UPDATE_ADMIN"
}